name: toma
favicon: null
layout_spectrum: 0.7460485144983977
typography_spectrum: 0.4851915508043021
title: A Toma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#625350'
    - '#b18c76'
    - '#0098d4'
  brandStrength: 0.5
  lightness: 0.7225751334335655
  saturation: 0.8600937298033386
  rhythmicContrast: 0.6604801840148866
purpose: []
