name: Andrew Toma
favicon: null
layout_spectrum: 0.76264
typography_spectrum: 1
title: Andrew Toma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#6f6f6f'
    - '#2b2b2b'
    - '#c7c7c7'
  brandStrength: 0.5
  lightness: 0.7225751334335655
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
