name: Andrew Toma
favicon: null
layout_spectrum: 0.7460485144983977
typography_spectrum: 0.23917
title: A Toma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#6a4938'
    - '#dcbf97'
    - '#4a2012'
    - '#757d72'
  brandStrength: 0.5
  lightness: 0.7225751334335655
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
